import { SalesChannelPreset } from "@/lib/types";

export const DEFAULT_PRESETS: SalesChannelPreset[] = [
  {
    key: "shopee",
    mode: "online",
    label: "Shopee",
    adminFee: 7.5,
    serviceFee: 1.5,
    paymentFee: 2,
    shippingProgramFee: 4,
    campaignFee: 1.5,
    affiliateFee: 5,
    adsFee: 3,
    taxFee: 0.5,
    fixedFee: 1250,
  },
  {
    key: "tokopedia",
    mode: "online",
    label: "Tokopedia",
    adminFee: 6,
    serviceFee: 1,
    paymentFee: 1.8,
    shippingProgramFee: 2.5,
    campaignFee: 1,
    affiliateFee: 3,
    adsFee: 2,
    taxFee: 0.5,
    fixedFee: 1000,
  },
  {
    key: "tiktok-shop",
    mode: "online",
    label: "TikTok Shop",
    adminFee: 6.5,
    serviceFee: 1.5,
    paymentFee: 2,
    shippingProgramFee: 3,
    campaignFee: 1.5,
    affiliateFee: 4,
    adsFee: 4,
    taxFee: 0.5,
    fixedFee: 1500,
  },
  {
    key: "lazada",
    mode: "online",
    label: "Lazada",
    adminFee: 5.5,
    serviceFee: 1,
    paymentFee: 1.7,
    shippingProgramFee: 2,
    campaignFee: 1,
    affiliateFee: 2.5,
    adsFee: 2,
    taxFee: 0.5,
    fixedFee: 1000,
  },
  {
    key: "gofood",
    mode: "online",
    label: "GoFood",
    adminFee: 20,
    serviceFee: 2,
    paymentFee: 1.5,
    shippingProgramFee: 0,
    campaignFee: 2,
    affiliateFee: 0,
    adsFee: 3,
    taxFee: 0.5,
    fixedFee: 1000,
  },
  {
    key: "grabfood",
    mode: "online",
    label: "GrabFood",
    adminFee: 20,
    serviceFee: 2,
    paymentFee: 1.5,
    shippingProgramFee: 0,
    campaignFee: 2,
    affiliateFee: 0,
    adsFee: 3,
    taxFee: 0.5,
    fixedFee: 1000,
  },
  {
    key: "shopeefood",
    mode: "online",
    label: "ShopeeFood",
    adminFee: 18,
    serviceFee: 2,
    paymentFee: 1.5,
    shippingProgramFee: 0,
    campaignFee: 2,
    affiliateFee: 0,
    adsFee: 3,
    taxFee: 0.5,
    fixedFee: 1000,
  },
  {
    key: "offline-store",
    mode: "offline",
    label: "Toko Offline",
    adminFee: 0,
    serviceFee: 0,
    paymentFee: 0.5,
    shippingProgramFee: 0,
    campaignFee: 0,
    affiliateFee: 0,
    adsFee: 1,
    taxFee: 0.5,
    fixedFee: 0,
  },
  {
    key: "offline-reseller",
    mode: "offline",
    label: "Reseller / Titip Jual",
    adminFee: 10,
    serviceFee: 0,
    paymentFee: 0,
    shippingProgramFee: 0,
    campaignFee: 0,
    affiliateFee: 0,
    adsFee: 0,
    taxFee: 0.5,
    fixedFee: 0,
  },
  {
    key: "custom",
    mode: "online",
    label: "Custom",
    adminFee: 0,
    serviceFee: 0,
    paymentFee: 0,
    shippingProgramFee: 0,
    campaignFee: 0,
    affiliateFee: 0,
    adsFee: 0,
    taxFee: 0,
    fixedFee: 0,
  },
];

export function getPresetByKey(key: SalesChannelPreset["key"]) {
  return DEFAULT_PRESETS.find((preset) => preset.key === key) ?? DEFAULT_PRESETS[0];
}
